### PR TITLE
GitHub Actions

### LINKED ISSUE #53: Replace Travis-CI with GHA
Copy from another project, e.g. https://github.com/dblock/ruby-enum

### PR DESCRIPTION
**Pull request by rchekaluk**
Fixes #53

### CODE REVIEW

**Review by dblock — CHANGES_REQUESTED** [review]
- change the CI/CD badge in README
- Add a separate workflow for Rubocop
- Add a line to https://github.com/txcrb/tax_cloud/blob/master/CHANGELOG.md

**Comment by rchekaluk** [comment]
Workflows are currently failing due to outage https://github.com/actions/runner/issues/1923

**Comment by rchekaluk** [comment]
Planning to submit a separate PR for Ruby 3 support.

**Comment by rchekaluk** [comment]
Done @dblock

**Comment by dblock** [comment]
Merged, thank you!

**Pull request merged**
